'use strict';
const root='../Assets/Resources/Varginha/Experiment/';
const $=id=>document.getElementById(id);
const storageKey='Varginha.Experiment.GDD.LDD.v1';
const assets={},lowCast=document.createElement('canvas');
const mapCanvas=document.createElement('canvas');
let data,state,puzzle=0,selected=-1,tab='opening',elapsed=0,playing=false,previous=0,spoken=-1,audioContext,noiseNode,gain;
const defaultState=()=>({version:1,openingSeen:false,mapSolved:false,documentsSolved:false,codeSolved:false,mapOrder:[...data.puzzles[0].initial],documentOrder:[...data.puzzles[1].initial],codeInput:''});
function validOrder(order){return Array.isArray(order)&&order.length===4&&[...order].sort().join(',')==='0,1,2,3'}
function loadState(){try{state=JSON.parse(localStorage.getItem(storageKey))}catch{}if(!state||state.version!==1)state=defaultState();if(!validOrder(state.mapOrder))state.mapOrder=[...data.puzzles[0].initial];if(!validOrder(state.documentOrder))state.documentOrder=[...data.puzzles[1].initial];if(!state.mapSolved){state.documentsSolved=false;state.codeSolved=false}if(!state.documentsSolved)state.codeSolved=false;if(!/^\d{0,4}$/.test(state.codeInput||''))state.codeInput=''}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(state));$('saveStatus').textContent='Progresso salvo neste navegador.'}catch{$('saveStatus').textContent='Armazenamento indisponível; mantenha a página aberta.'}}
function canOpen(index){return index===0||index===1&&state.mapSolved||index===2&&state.documentsSolved}
function solved(index){return index===0?state.mapSolved:index===1?state.documentsSolved:state.codeSolved}
function setTab(next){tab=next;for(const id of ['opening','investigate','characters'])$(id).classList.toggle('hidden',id!==next);if(next!=='opening'){playing=false;stopSound();$('play').textContent='CONTINUAR PRÉVIA'}if(next==='investigate')renderPuzzle()}
function loadImage(name){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{assets[name]=image;resolve()};image.onerror=()=>reject(new Error('Arte ausente: '+name));image.src=root+name+'.png'})}
function character(canvas,cell){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,64,64);ctx.drawImage(lowCast,(cell%2)*64,cell<2?0:64,64,64,0,0,64,64)}
function buildMap(){mapCanvas.width=160;mapCanvas.height=112;const ctx=mapCanvas.getContext('2d');for(let y=0;y<112;y++)for(let x=0;x<160;x++){const n=(x*13+y*7)%11;ctx.fillStyle='rgb('+(184+n)+','+(169+n)+','+(120+n)+')';ctx.fillRect(x,111-y,1,1)}const dot=(x,y,color)=>{ctx.fillStyle=color;ctx.fillRect(x,111-y,1,1)};for(let y=0;y<112;y++){const x=103+Math.round(Math.sin(y*.07)*17);for(let d=-4;d<=4;d++)dot(x+d,y,'#3d6b73')}for(let x=0;x<160;x++){const y=27+Math.floor(x/3);for(let d=-1;d<=1;d++)dot(x,y+d,'#634430')}for(let tree=0;tree<48;tree++){const tx=(tree*43+18)%160,ty=(tree*29+6)%112;if(tx<56&&ty>60)continue;for(let dy=0;dy<6;dy++)for(let dx=-Math.floor(dy/2);dx<=Math.floor(dy/2);dx++)dot(tx+dx,ty+dy,'#5e7142')}for(let y=74;y<88;y++)for(let x=19;x<34;x++)dot(x,y,'#dad0af');for(let y=88;y<92;y++)for(let x=16;x<37;x++)dot(x,y,'#634430');for(let y=90;y<98;y++)dot(26,y,'#634430');for(let x=23;x<30;x++)dot(x,95,'#634430');for(let x=97;x<120;x++)for(let y=57;y<60;y++)dot(x,y,'#634430')}
function renderPuzzle(){const p=data.puzzles[puzzle];$('puzzleTitle').textContent=p.title;$('puzzleDescription').textContent=p.description;$('caseNav').replaceChildren();data.puzzles.forEach((item,index)=>{const b=document.createElement('button');b.textContent=(solved(index)?'✓ ':'')+(index+1)+'. '+item.title;b.disabled=!canOpen(index);b.onclick=()=>{puzzle=index;selected=-1;$('feedback').textContent='';renderPuzzle()};$('caseNav').append(b)});$('pieces').replaceChildren();$('pieces').classList.toggle('hidden',puzzle===2);$('codePuzzle').classList.toggle('hidden',puzzle!==2);if(puzzle<2){const order=puzzle===0?state.mapOrder:state.documentOrder;order.forEach((piece,index)=>{const b=document.createElement('button');b.className='piece '+(puzzle===1?'doc ':'')+(selected===index?'selected':'');b.setAttribute('aria-label','Posição '+(index+1)+': '+p.items[piece]);b.setAttribute('aria-pressed',selected===index?'true':'false');if(puzzle===0){const canvas=document.createElement('canvas');canvas.width=80;canvas.height=56;const visual=[1,3,0,2][piece];canvas.getContext('2d').drawImage(mapCanvas,(visual%2)*80,visual<2?0:56,80,56,0,0,80,56);b.append(canvas);const label=document.createElement('small');label.textContent=p.items[piece];b.append(label)}else b.textContent=p.items[piece];b.onclick=()=>{if(selected<0)selected=index;else{[order[selected],order[index]]=[order[index],order[selected]];selected=-1;save()}$('feedback').textContent='';renderPuzzle()};$('pieces').append(b)})}else{$('clues').replaceChildren();p.items.forEach(item=>{const line=document.createElement('p');line.textContent=item;$('clues').append(line)});$('code').value=state.codeInput||''}character($('speaker'),puzzle===1?2:1);$('helper').textContent=solved(puzzle)?p.reward:'Compare os recortes, as datas e os símbolos. As pistas não são destruídas por tentativas incorretas.';$('progress').textContent=[state.mapSolved,state.documentsSolved,state.codeSolved].filter(Boolean).length+' / 3 investigações concluídas.'}
function check(){const p=data.puzzles[puzzle],order=puzzle===0?state.mapOrder:state.documentOrder;const ok=canOpen(puzzle)&&(puzzle===2?state.codeInput===p.code:order.every((item,index)=>item===p.solution[index]));if(ok){if(puzzle===0)state.mapSolved=true;else if(puzzle===1)state.documentsSolved=true;else state.codeSolved=true;save();renderPuzzle();$('feedback').textContent=p.reward}else $('feedback').textContent='Ainda há uma contradição. Confira as conexões e tente novamente.'}
function shotAt(time){let start=0;for(let index=0;index<data.shots.length;index++){const s=data.shots[index];if(time<start+s.duration)return {s,index,time:time-start};start+=s.duration}const index=data.shots.length-1;return {s:data.shots[index],index,time:data.shots[index].duration}}
function draw(){if(!data)return;const ctx=$('cinema').getContext('2d');ctx.imageSmoothingEnabled=false;const {s,index,time}=shotAt(elapsed);ctx.fillStyle='#000';ctx.fillRect(0,0,384,216);const image=assets[s.asset];if(s.mode!=='timeskip'){const sw=s.panel<0?image.width:image.width/2,sh=s.panel<0?image.height:image.height/2;const sx=s.panel<0?0:(s.panel%2)*sw,sy=s.panel<0?0:s.panel<2?0:sh;const shift=!$('reduced').checked&&s.mode==='street'?Math.min(5,Math.floor(time/2)):0;ctx.drawImage(image,sx+shift,sy,sw-shift,sh,0,0,384,216);ctx.fillStyle='#0002';for(let y=0;y<216;y+=2)ctx.fillRect(0,y,384,1);if(!$('reduced').checked&&(s.mode==='interference'||s.mode==='signal')){const tick=Math.floor(time*12);ctx.fillStyle=s.mode==='signal'?'#102028e0':'#70908040';for(let y=0;y<216;y+=3){const x=(y*73+tick*47)%384;ctx.fillRect(x,y,32,2)}}if(s.mode==='flash'&&!$('reduced').checked){ctx.fillStyle='rgba(225,239,225,'+Math.min(1,time/2.5)+')';ctx.fillRect(0,0,384,216)}}$('shotTitle').textContent=s.title;$('subtitle').textContent=s.subtitle;$('time').textContent=Math.floor(elapsed)+' / '+duration()+' s';$('seek').value=elapsed;if(playing&&index!==spoken){spoken=index;if($('sound').checked&&s.voice)speak(s.subtitle)}}
function duration(){return data.shots.reduce((sum,s)=>sum+s.duration,0)}
function speak(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(text);speech.lang='pt-BR';speech.rate=.88;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('pt-br'));if(voice)speech.voice=voice;window.speechSynthesis.speak(speech)}
function startSound(){if(!$('sound').checked)return;if(!audioContext){audioContext=new (window.AudioContext||window.webkitAudioContext)();const buffer=audioContext.createBuffer(1,audioContext.sampleRate,audioContext.sampleRate);const arr=buffer.getChannelData(0);let seed=96;for(let i=0;i<arr.length;i++){seed=(seed*1664525+1013904223)>>>0;arr[i]=((seed>>>8)%1000)/1000-.5}noiseNode=audioContext.createBufferSource();noiseNode.buffer=buffer;noiseNode.loop=true;gain=audioContext.createGain();gain.gain.value=.015;noiseNode.connect(gain).connect(audioContext.destination);noiseNode.start()}audioContext.resume();if(gain)gain.gain.value=.015}
function stopSound(){if(gain)gain.gain.value=0;if(window.speechSynthesis)window.speechSynthesis.cancel()}
function finish(){elapsed=duration();playing=false;state.openingSeen=true;save();stopSound();setTab('investigate');$('feedback').textContent='2026 • Renan está na Industrial. Comece pelos fragmentos do mapa.'}
function tick(now){if(previous&&playing){elapsed=Math.min(duration(),elapsed+(now-previous)/1000);if(elapsed>=duration())finish()}previous=now;if(tab==='opening')draw();requestAnimationFrame(tick)}
async function start(){try{data=await (await fetch(root+'ExperimentDefinition.json')).json();await Promise.all(['OpeningStoryboard','IndustrialFacade','GameCast'].map(loadImage));lowCast.width=lowCast.height=128;const c=lowCast.getContext('2d');c.imageSmoothingEnabled=false;c.drawImage(assets.GameCast,0,0,128,128);buildMap();loadState();$('seek').max=duration();$('loading').classList.add('hidden');setTab('opening');draw();data.characters.forEach(person=>{const card=document.createElement('article'),canvas=document.createElement('canvas');canvas.width=canvas.height=64;character(canvas,person.cell);card.append(canvas);const h=document.createElement('h2');h.textContent=person.name;card.append(h);const role=document.createElement('p');role.className='eyebrow';role.textContent=person.role;card.append(role);const text=document.createElement('p');text.textContent=person.description;card.append(text);$('cast').append(card)});requestAnimationFrame(tick)}catch(error){$('loading').textContent='Não foi possível abrir a prévia: '+error.message}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('play').onclick=()=>{if(elapsed>=duration())elapsed=0;playing=!playing;spoken=-1;if(playing)startSound();else stopSound();$('play').textContent=playing?'PAUSAR':'CONTINUAR PRÉVIA'};
$('skip').onclick=finish;$('replay').onclick=()=>{elapsed=0;spoken=-1;playing=true;startSound();$('play').textContent='PAUSAR';draw()};
$('seek').oninput=event=>{elapsed=Number(event.target.value);spoken=-1;stopSound();draw()};
$('sound').onchange=()=>{spoken=-1;if($('sound').checked&&playing)startSound();else stopSound()};
$('check').onclick=check;$('hint').onclick=()=>{$('helper').textContent=data.puzzles[puzzle].hint};
$('resetPieces').onclick=()=>{if(puzzle===0)state.mapOrder=[...data.puzzles[0].initial];else if(puzzle===1)state.documentOrder=[...data.puzzles[1].initial];else state.codeInput='';selected=-1;save();renderPuzzle();$('feedback').textContent='Peças reorganizadas; as descobertas já feitas foram preservadas.'};
$('code').oninput=event=>{state.codeInput=event.target.value.replace(/\D/g,'').slice(0,4);event.target.value=state.codeInput;save()};
$('code').onkeydown=event=>{if(event.key==='Enter')check()};
$('newTest').onclick=()=>{state=defaultState();puzzle=0;selected=-1;save();renderPuzzle();$('feedback').textContent='Novo experimento iniciado.'};
window.addEventListener('beforeunload',stopSound);document.addEventListener('visibilitychange',()=>{if(document.hidden){playing=false;stopSound();$('play').textContent='CONTINUAR PRÉVIA'}});
start();
